services:
  webserver:
    ports:
      - "${FORWARD_APP_PORT:-8000}:80"
    volumes:
      - ./server/docker/nginx/conf.d/dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./server:/var/www
      - ./server/public:/var/www/public
  app:
    build:
      context: ./server
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ./server:/var/www
      - ./server/.env:/var/www/.env
      - ./server/public:/var/www/public
    environment:
      PHP_IDE_CONFIG: "serverName=docker-xdebug"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: sh -c "php artisan config:clear && php-fpm"

  queue:
    build:
      context: ./server
      dockerfile: docker/Dockerfile.dev
    command: php artisan queue:listen --sleep=1 --tries=3
    volumes:
      - ./server:/var/www
      - ./server/.env:/var/www/.env

  scheduler:
    build:
      context: ./server
      dockerfile: docker/Dockerfile.dev
    command: php artisan schedule:work
    volumes:
      - ./server:/var/www
      - ./server/.env:/var/www/.env

  mysql:
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"

  redis:
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"

  sse:
    ports:
      - "${FORWARD_SSE_PORT:-8080}:8080"
    env_file:
      - ./sse/.env

  # ServiÃ§os exclusivos de DEV
  composer:
    build:
      context: ./server
      dockerfile: docker/Dockerfile.dev
    working_dir: /var/www
    volumes:
      - ./server:/var/www
    entrypoint: [ "composer", "--ansi", "--no-interaction", "--no-progress" ]

  mailpit:
    image: axllent/mailpit:v1.29
    ports:
      - "${FORWARD_MAILPIT_PORT:-8025}:8025"
    networks:
      - vinmo-network
    environment:
      MP_MAX_MESSAGES: 5000

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    command: server /data --console-address ":9001"
    ports:
      - "${FORWARD_MINIO_PORT:-9000}:9000"
      - "${FORWARD_MINIO_CONSOLE_PORT:-9001}:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data
    networks:
      - vinmo-network

  minio-setup:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    depends_on:
      - minio
    entrypoint: >
      sh -c "
        mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
        mc mb -p local/vinmo-dev || true &&
        mc anonymous set download local/vinmo-dev
      "
    networks:
      - vinmo-network

volumes:
  minio-data: