services:
  webserver:
    image: nginx:alpine
    ports:
      - "8001:80"
    volumes:
      - ./server/docker/nginx/conf.d/prod.conf:/etc/nginx/conf.d/default.conf
      - assets_volume:/var/www/public
    depends_on:
      - app
    networks:
      - vinmo-network

  # Aplicação PHP-FPM
  app:
    build:
      context: ./server
      dockerfile: docker/Dockerfile
    working_dir: /var/www
    volumes:
      - ./server/storage:/var/www/storage
      - assets_volume:/var/www/public
    env_file:
      - ./server/.env
    depends_on:
      - mysql
      - redis
    command: sh -c "php artisan config:cache && php artisan route:cache && php artisan view:cache && php-fpm"
    networks:
      - vinmo-network

  # Fila (Queue Worker)
  queue:
    build:
      context: ./server
      dockerfile: docker/Dockerfile
    working_dir: /var/www
    command: php artisan queue:work --tries=3 --timeout=90
    env_file:
      - ./server/.env
    depends_on:
      - app
      - redis
      - mysql
    restart: always
    networks:
      - vinmo-network

  # Scheduler (Cron)
  scheduler:
    build:
      context: ./server
      dockerfile: docker/Dockerfile
    working_dir: /var/www
    command: php artisan schedule:work
    env_file:
      - ./server/.env
    depends_on:
      - app
      - mysql
    restart: always
    networks:
      - vinmo-network

  # Banco de Dados
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-prod-data:/var/lib/mysql
    restart: always
    networks:
      - vinmo-network

  # Cache / Session
  redis:
    image: redis:8-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    volumes:
      - redis-prod-data:/data
    restart: always
    networks:
      - vinmo-network

  sse:
    build:
      context: ./sse
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - redis
    networks:
      - vinmo-network

volumes:
  mysql-prod-data:
  redis-prod-data:
  assets_volume:

networks:
  vinmo-network:
    driver: bridge
