services:
  webserver:
    image: nginx:alpine
    depends_on:
      - app
    networks:
      - vinmo-network

  app:
    env_file:
      - ./server/.env
    environment:
      DB_CONNECTION: mysql
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT:-6379}
    build:
      context: ./server
      dockerfile: docker/Dockerfile
    working_dir: /var/www
    networks:
      - vinmo-network
    depends_on:
      - mysql
      - redis

  queue:
    env_file:
      - ./server/.env
    environment:
      DB_CONNECTION: mysql
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
    build:
      context: ./server
      dockerfile: docker/Dockerfile
    working_dir: /var/www
    networks:
      - vinmo-network
    depends_on:
      - app
      - redis
      - mysql

  scheduler:
    env_file:
      - ./server/.env
    environment:
      DB_CONNECTION: mysql
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
    build:
      context: ./server
      dockerfile: docker/Dockerfile
    working_dir: /var/www
    networks:
      - vinmo-network
    depends_on:
      - app
      - mysql

  sse:
    env_file:
      - ./sse/.env
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
    build:
      context: ./sse
      dockerfile: Dockerfile
    depends_on:
      - redis
    networks:
      - vinmo-network

volumes:
  mysql-data:
  redis-data:
  assets_volume:

networks:
  vinmo-network:
    driver: bridge