services:
  webserver:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./server/docker/nginx/conf.d/dev.conf:/etc/nginx/conf.d/default.conf
      - ./server:/var/www # Monta o cÃ³digo local para o Nginx servir assets se precisar
    depends_on:
      - app

  app:
    build:
      context: ./server
      dockerfile: docker/Dockerfile.dev
    working_dir: /var/www
    volumes:
      - ./server:/var/www
    env_file:
      - ./server/.env
    depends_on:
      - mysql
      - redis
      - mailpit
      - minio
      - minio-setup
    environment:
      PHP_IDE_CONFIG: "serverName=docker-xdebug"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  queue:
    build:
      context: ./server
      dockerfile: docker/Dockerfile.dev
    working_dir: /var/www
    command: php artisan queue:listen --sleep=1 --tries=3
    volumes:
      - ./server:/var/www
    env_file:
      - ./server/.env
    depends_on:
      - app
      - redis

  scheduler:
    build:
      context: ./server
      dockerfile: docker/Dockerfile.dev
    working_dir: /var/www
    command: php artisan schedule:work
    volumes:
      - ./server:/var/www
    env_file:
      - ./server/.env
    depends_on:
      - app

  composer:
    build:
      context: ./server
      dockerfile: docker/Dockerfile.dev
    working_dir: /var/www
    volumes:
      - ./server:/var/www
    entrypoint: [ "composer", "--ansi", "--no-interaction", "--no-progress" ]

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vinmo
      MYSQL_USER: vinmo
      MYSQL_PASSWORD: vinmo
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:8-alpine

  sse:
    build:
      context: ./sse
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
    depends_on:
      - redis

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"
    environment:
      MP_MAX_MESSAGES: 5000

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console
    volumes:
      - minio-data:/data

  # CRIA O BUCKET
  minio-setup:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      sh -c "
        mc alias set local http://minio:9000 minio minio12345 &&
        mc mb -p local/vinmo-dev || true &&
        mc anonymous set download local/vinmo-dev
      "
    environment:
      MC_HOST_local: http://minio:minio12345@minio:9000

volumes:
  mysql-data:
  minio-data:
  composer-cache:
